using System.Reflection;
using System.Text;
using SwiftlyS2.Shared;

namespace SwiftlyBhopTimer.Services;

public sealed class RoundFlowConfigService
{
    private static readonly IReadOnlyList<(string Name, string Value)> MaintainedConvars =
    [
        ("mp_warmup_pausetimer", "0"),
        ("mp_warmup_offline_enabled", "0"),
        ("mp_warmup_online_enabled", "0"),
        ("mp_warmuptime", "0"),
        ("mp_warmuptime_all_players_connected", "0"),
        ("mp_freezetime", "0"),
        ("mp_team_intro_time", "0"),
        ("game_type", "3"),
        ("game_mode", "0"),
        ("mp_halftime", "0"),
        ("mp_overtime_enable", "0"),
        ("mp_round_restart_delay", "0"),
        ("mp_ignore_round_win_conditions", "1"),
        ("mp_respawn_on_death_ct", "0"),
        ("mp_respawn_on_death_t", "0"),
        ("mp_respawn_immunitytime", "-1"),
        ("mp_endmatch_votenextmap", "0"),
        ("mp_endmatch_votenextleveltime", "0"),
        ("mp_endmatch_votenextmap_keepcurrent", "0"),
        ("mp_match_end_changelevel", "1"),
        ("mp_match_end_restart", "0"),
        ("mp_match_restart_delay", "0"),
        ("mp_win_panel_display_time", "0"),
        ("sv_warmup_to_freezetime_delay", "0"),
        ("mp_solid_teammates", "0"),
        ("mp_solid_enemies", "0"),
        ("mp_friendlyfire", "0"),
        ("mp_autoteambalance", "0"),
        ("mp_limitteams", "0"),
        ("mp_humanteam", "any"),
        ("mp_force_pick_time", "0"),
        ("bot_quota_mode", "normal"),
        ("bot_quota", "5"),
        ("bot_join_after_player", "0"),
        ("bot_auto_vacate", "0"),
        ("bot_controllable", "0"),
        ("mp_disconnect_kills_bots", "0"),
        ("ff_damage_bullet_penetration", "0"),
        ("ff_damage_reduction_bullets", "0"),
        ("ff_damage_reduction_grenade", "0"),
        ("ff_damage_reduction_grenade_self", "0"),
        ("ff_damage_reduction_other", "0"),
        ("sv_infinite_ammo", "2"),
        ("sv_noclipspeed", "5"),
        ("sv_noclipaccelerate", "5"),
        ("sv_falldamage_scale", "0"),
        ("sv_staminajumpcost", "0"),
        ("sv_staminalandcost", "0"),
        ("sv_staminarecoveryrate", "60"),
        ("sv_staminamax", "0")
    ];

    private static readonly IReadOnlyList<(string Name, string Value)> BaseConvars =
    [
        .. MaintainedConvars,
        ("sv_jump_precision_enable", "0"),
        ("sv_legacy_jump", "1"),
        ("sv_subtick_movement_view_angles", "0"),
        ("mp_maxrounds", "0"),
        ("mp_autokick", "0"),
        ("mp_autoteambalance", "0"),
        ("mp_limitteams", "0"),
        ("mp_humanteam", "any"),
        ("mp_forcecamera", "0"),
        ("mp_force_pick_time", "0"),
        ("bot_quota_mode", "normal"),
        ("bot_quota", "5"),
        ("mp_randomspawn", "0"),
        ("mp_randomspawn_los", "0"),
        ("sv_disconnected_players_cleanup_delay", "1"),
        ("mp_spectators_max", "64"),
        ("mp_suicide_penalty", "0"),
        ("mp_buytime", "0"),
        ("mp_free_armor", "2"),
        ("mp_give_player_c4", "0"),
        ("mp_disconnect_kills_players", "0"),
        ("mp_death_drop_c4", "0"),
        ("mp_death_drop_defuser", "0"),
        ("mp_death_drop_gun", "0"),
        ("mp_death_drop_grenade", "0"),
        ("mp_drop_knife_enable", "0"),
        ("sv_show_teammate_death_notification", "0"),
        ("sv_disable_radar", "1"),
        ("mp_afterroundmoney", "16000"),
        ("mp_startmoney", "16000"),
        ("mp_playercashawards", "0"),
        ("mp_teamcashawards", "0"),
        ("mp_weapons_allow_map_placed", "0"),
        ("mp_ct_default_primary", ""),
        ("mp_ct_default_secondary", "weapon_usp_silencer"),
        ("mp_t_default_primary", ""),
        ("mp_t_default_secondary", "weapon_usp_silencer"),
        ("sv_vote_allow_in_warmup", "0"),
        ("sv_vote_allow_spectators", "0"),
        ("sv_deadtalk", "1"),
        ("sv_full_alltalk", "1")
    ];

    private readonly ISwiftlyCore _core;
    private readonly string _configPath;
    private DateTime _lastMaintainedApplyUtc = DateTime.MinValue;
    private bool _executeWarningLogged;
    private bool _warmupReflectionWarningLogged;

    public RoundFlowConfigService(ISwiftlyCore core, string configPath)
    {
        _core = core;
        _configPath = configPath;
    }

    public string ConfigPath => _configPath;

    public void WriteConfig()
    {
        var directory = Path.GetDirectoryName(_configPath);
        if (!string.IsNullOrWhiteSpace(directory))
        {
            Directory.CreateDirectory(directory);
        }

        var builder = new StringBuilder();
        builder.AppendLine("// Generated by SwiftlyBhopTimer.");
        builder.AppendLine("// This file is overwritten when the plugin loads.");
        builder.AppendLine("// It disables warmup/round presentation and keeps bhop timer maps playable.");
        builder.AppendLine();

        foreach (var (name, value) in BaseConvars.DistinctBy(item => item.Name))
        {
            builder.AppendLine(ToCommand(name, value));
        }

        builder.AppendLine("mp_warmup_end");
        File.WriteAllText(_configPath, builder.ToString(), Encoding.UTF8);
    }

    public void ApplyFull(bool includeTimeLimit = false)
    {
        foreach (var (name, value) in BaseConvars.DistinctBy(item => item.Name))
        {
            Execute(ToCommand(name, value));
        }

        Execute("sbt_roundflow_apply");
        EndWarmup();
        _lastMaintainedApplyUtc = DateTime.UtcNow;
    }

    public void ApplyMaintainedIfDue()
    {
        var now = DateTime.UtcNow;
        if ((now - _lastMaintainedApplyUtc).TotalSeconds < 1)
        {
            return;
        }

        _lastMaintainedApplyUtc = now;
        foreach (var (name, value) in MaintainedConvars)
        {
            Execute(ToCommand(name, value));
        }

        EndWarmup();
    }

    private void EndWarmup()
    {
        ForceWarmupStateOff();
        Execute("mp_warmup_end");
        Execute("mp_unpause_match");
    }

    private void Execute(string command)
    {
        try
        {
            _core.Engine.ExecuteCommand(command);
        }
        catch (Exception ex)
        {
            if (!_executeWarningLogged)
            {
                _executeWarningLogged = true;
                Console.WriteLine($"[SwiftlyBhopTimer] Failed to execute server cfg command '{command}': {ex.Message}");
            }
        }
    }

    private void ForceWarmupStateOff()
    {
        try
        {
            var gameRules = _core.EntitySystem.GetGameRules();
            if (gameRules is null)
            {
                return;
            }

            SetBoolIfExists(
                gameRules,
                false,
                "WarmupPeriod",
                "IsWarmupPeriod",
                "GameWarmup",
                "Warmup",
                "m_bWarmupPeriod",
                "m_bIsWarmupPeriod");
            SetIntIfExists(
                gameRules,
                0,
                "WarmupTime",
                "WarmupStartTime",
                "WarmupEndTime",
                "WarmupPeriodEnd",
                "m_iWarmupTime",
                "m_iWarmupStartTime",
                "m_iWarmupEndTime");
            SetFloatIfExists(
                gameRules,
                0,
                "WarmupTime",
                "WarmupStartTime",
                "WarmupEndTime",
                "WarmupPeriodEnd",
                "m_fWarmupPeriodEnd",
                "m_flWarmupPeriodEnd",
                "m_flWarmupStartTime",
                "m_flWarmupEndTime");
        }
        catch (Exception ex)
        {
            if (!_warmupReflectionWarningLogged)
            {
                _warmupReflectionWarningLogged = true;
                Console.WriteLine($"[SwiftlyBhopTimer] Failed to force warmup state off: {ex.Message}");
            }
        }
    }

    private static string ToCommand(string name, string value)
    {
        return string.IsNullOrEmpty(value)
            ? $"{name} \"\""
            : $"{name} {value}";
    }

    private static void SetBoolIfExists(object target, bool value, params string[] names)
    {
        foreach (var name in names)
        {
            SetMemberIfExists(target, name, value);
        }
    }

    private static void SetIntIfExists(object target, int value, params string[] names)
    {
        foreach (var name in names)
        {
            SetMemberIfExists(target, name, value);
        }
    }

    private static void SetFloatIfExists(object target, float value, params string[] names)
    {
        foreach (var name in names)
        {
            SetMemberIfExists(target, name, value);
        }
    }

    private static void SetMemberIfExists(object target, string name, object value)
    {
        const BindingFlags flags = BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic;
        var type = target.GetType();

        var property = type.GetProperty(name, flags);
        if (property is not null && property.CanWrite)
        {
            TrySetValue(target, property.PropertyType, value, converted =>
            {
                property.SetValue(target, converted);
                InvokeNoArg(target, $"{name}Updated");
            });
            return;
        }

        var field = type.GetField(name, flags);
        if (field is not null)
        {
            TrySetValue(target, field.FieldType, value, converted =>
            {
                field.SetValue(target, converted);
                InvokeNoArg(target, $"{name}Updated");
            });
        }
    }

    private static void TrySetValue(object target, Type destinationType, object value, Action<object> setter)
    {
        try
        {
            var converted = Convert.ChangeType(value, destinationType, System.Globalization.CultureInfo.InvariantCulture);
            setter(converted);
        }
        catch
        {
            _ = target;
        }
    }

    private static void InvokeNoArg(object target, string methodName)
    {
        target.GetType()
            .GetMethod(methodName, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, binder: null, types: Type.EmptyTypes, modifiers: null)
            ?.Invoke(target, null);
    }
}
